image: python:3.8

cache:
  - paths:
      - .cache/pip
      - .cache/pre-commit
    when: always
  - key:
      prefix: myst-nb
      files:
        - .constraints/*.txt
        - data/*
        # https://gitlab.com/gitlab-org/gitlab/-/issues/301161
        # - src/polarimetry/*.py
        # - src/polarimetry/*/*.py
    paths:
      - docs/_build/.jupyter_cache
      - docs/_images
      - docs/_static/export
      - docs/_static/images
      - docs/appendix/export
    when: always
  - key:
      prefix: sympy
      files:
        - .constraints/*.txt
    paths:
      - .sympy-cache-jax
      - .sympy-cache
    when: always

pre-commit:
  stage: test
  before_script:
    - python3 -m pip install -e .[sty] -c .constraints/py3.8.txt
  script:
    - pre-commit run -a --color always

pytest:
  stage: test
  before_script:
    - python3 -m pip install .[test] tox -c .constraints/py3.8.txt
  script:
    - pytest

documentation:
  stage: build
  before_script:
    - apt-get update
    - apt-get install -y cm-super dvipng inkscape latexmk texlive-fonts-extra texlive-latex-extra texlive-xetex xindy
    - python3 -m pip install .[doc] tox -c .constraints/py3.8.txt
    - wget -q https://julialang-s3.julialang.org/bin/linux/x64/1.7/julia-1.7.3-linux-x86_64.tar.gz
    - tar xzf julia-1.7.3-linux-x86_64.tar.gz
    - mv julia-1.7.3 /opt/
    - ln -s /opt/julia-1.7.3/bin/julia /usr/local/bin/julia
    - julia --project=./julia -e 'import Pkg; Pkg.instantiate()'
  script:
    - tox -e pdfnb
    - tar czf latex.tar.gz -C docs/_build/latex/
    - EXECUTE_PLUTO="YES" tox -e docnb
  artifacts:
    paths:
      - docs/_build/html/
      - latex.tar.gz
    when: always

pages:
  stage: deploy
  dependencies:
    - documentation
  only:
    - main
    - tags
  script:
    - mv docs/_build/html/ public/
  artifacts:
    paths:
      - public
    when: always

stages:
  - test
  - build
  - deploy

# https://docs.gitlab.com/ee/ci/caching/#cache-python-dependencies
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PRE_COMMIT_HOME: "$CI_PROJECT_DIR/.cache/pre-commit"
  PYTHONHASHSEED: "0"
  SYMPY_CACHE_DIR: "$CI_PROJECT_DIR"
