image: python:3.8

pages:
  only:
    - main
  before_script:
    - apt-get update
    - apt-get install -y cm-super dvipng inkscape latexmk texlive-fonts-extra texlive-latex-extra texlive-xetex xindy
    - python3 -m pip install .[doc] tox -c .constraints/py3.8.txt
    - wget -q https://julialang-s3.julialang.org/bin/linux/x64/1.7/julia-1.7.3-linux-x86_64.tar.gz
    - tar xzf julia-1.7.3-linux-x86_64.tar.gz
    - mv julia-1.7.3 /opt/
    - ln -s /opt/julia-1.7.3/bin/julia /usr/local/bin/julia
    - julia --project=./julia -e 'import Pkg; Pkg.instantiate()'
  script:
    - tox -e pdfnb
    - EXECUTE_PLUTO="YES" tox -e docnb
    - mv docs/_build/html/ public/
    - tar czf public/latex.tar.gz -C docs/_build/ latex/
  artifacts:
    paths:
      - public
    when: always
  cache:
    paths:
      - .cache/pip
      - .sympy-cache-jax
      - .sympy-cache
      - docs/_build/.jupyter_cache
      - docs/_images
      - docs/_static/images
      - docs/appendix/export
      - docs/export

# https://docs.gitlab.com/ee/ci/caching/#cache-python-dependencies
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PYTHONHASHSEED: "0"
  SYMPY_CACHE_DIR: "$CI_PROJECT_DIR"
