image: python:3.8

docs:
  only:
    - PDF-documentation
    - main
  before_script:
    - apt-get update
    - apt-get install -y cm-super dvipng inkscape latexmk texlive-fonts-extra texlive-latex-extra texlive-xetex
    - python3 -m pip install .[doc]
  script:
    - cd docs
    - make latex
    - cd _build/latex
    - make LATEXMKOPTS=' -f' LATEXOPTS=' -interaction=batchmode'
    # Check if there are there are missing figures in the PDF build
    - ! grep -r '\PYGZlt{}Figure size ' .
    - cd ../..
    - sphinx-build -nW --color --keep-going -b html docs/ public
  variables:
    EXECUTE_NB: "YES"
    EXECUTE_PLUTO: "YES"
    PYTHONHASHSEED: "0"
  artifacts:
    paths:
      - public
