version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
  jobs:
    pre_build:
      - jupyter-book config sphinx research/

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc

sphinx:
  builder: html
  configuration: research/conf.py
  fail_on_warning: true
