name: polarimetry
channels:
  - defaults
dependencies:
  - python==3.8.*
  - pip>=21.3 # pyproject.toml
  - pip:
      - |
        -c .constraints/py3.8.txt
        -e .[dev]
variables:
  PYTHONHASHSEED: 0
  PRETTIER_LEGACY_CLI: "1"
