[project]
channels = [
    "conda-forge",
    "https://repo.prefix.dev/julia-forge",
]
name = "polarimetry-lc2pkpi"
platforms = [
    "linux-64",
    "osx-64",
    "osx-arm64",
]

[dependencies]
julia = {version = "*", channel = "https://repo.prefix.dev/julia-forge"}
uv = "*"
