FROM python:3.9
RUN apt-get -y update

# https://serverfault.com/a/992421
RUN DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get -y install tzdata
RUN apt-get -y install \
    inkscape \
    latexmk \
    make \
    texlive-fonts-extra \
    texlive-xetex \
    xindy \
    && apt-get autoclean -y \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/*
