#!/bin/bash
set -ex
curl -LsSf https://pixi.sh/install.sh | bash
export PATH="$HOME/.pixi/bin:$PATH"

pixi_packages="$(NO_COLOR= pixi list --explicit --no-install | awk 'NR > 1 {print $1}')"
if [[ -n "$pixi_packages" ]]; then
  pixi global install $pixi_packages
fi
pixi clean cache --yes

uv export \
  --group jupyter \
  --group notebooks \
  --no-dev \
  > requirements.txt
uv pip install \
  --requirement requirements.txt \
  --system
uv cache clean
