name: Documentation
env:
  JULIA_CI: "true"
  PYTHONHASHSEED: "0"
  PYTHON_VERSION: "3.8"

on:
  push:
    branches:
      - main
      - epic/*
      - "[0-9]+.[0-9]+.x"
  pull_request:
    branches:
      - main
      - epic/*
      - "[0-9]+.[0-9]+.x"
  workflow_dispatch:

jobs:
  fast-html:
    name: Build HTML (fast)
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{env.PYTHON_VERSION}}
      - uses: actions/cache@v3
        with:
          key: pip-doc-${{runner.os}}-py${{env.PYTHON_VERSION}}-${{ hashFiles('.constraints/py3.*.txt', 'setup.cfg') }}
          path: ~/.cache/pip/
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[doc] tox -c .constraints/py${PYTHON_VERSION}.txt
      - run: tox -e doc
      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: html
          path: docs/_build/html

  fast-pdf:
    name: Build PDF (fast)
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{env.PYTHON_VERSION}}
      - uses: actions/cache@v3
        with:
          key: pip-doc-${{runner.os}}-py${{env.PYTHON_VERSION}}-${{ hashFiles('.constraints/py3.*.txt', 'setup.cfg') }}
          path: ~/.cache/pip/
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[doc] tox -c .constraints/py${PYTHON_VERSION}.txt
      # cspell:ignore awalsh pkgs
      - uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: inkscape latexmk make texlive-fonts-extra texlive-xetex xindy
          version: 1.0
      - run: tox -e pdf
      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: latex
          path: docs/_build/latex

  linkcheck:
    name: Check external links
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{env.PYTHON_VERSION}}
      - uses: actions/cache@v3
        with:
          key: pip-doc-${{runner.os}}-py${{env.PYTHON_VERSION}}-${{ hashFiles('.constraints/py3.*.txt', 'setup.cfg') }}
          path: ~/.cache/pip/
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[doc] tox -c .constraints/py${PYTHON_VERSION}.txt
      - run: tox -e linkcheck

  documentation:
    name: Run notebooks and build documentation
    needs:
      - fast-html
      - fast-pdf
      - linkcheck
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{env.PYTHON_VERSION}}
      - uses: actions/cache@v3
        with:
          key: pip-doc-${{runner.os}}-py${{env.PYTHON_VERSION}}-${{ hashFiles('.constraints/py3.*.txt', 'setup.cfg') }}
          path: ~/.cache/pip/
      - name: Install Python and APT dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[doc] tox -c .constraints/py${PYTHON_VERSION}.txt
          sudo apt-get -y install cm-super dvipng inkscape latexmk texlive-fonts-extra texlive-latex-extra texlive-xetex xindy
      - uses: actions/cache@v3
        with:
          key: |
            ${{ github.workflow }}-${{ github.job }}-${{ runner.os }}-${{ hashFiles('.constraints/py3.*.txt', 'data/**', 'julia/Manifest.toml', 'julia/Project.toml', 'setup.cfg', 'src/**') }}
          path: |
            ./docs/_build/.jupyter_cache
            ./docs/_images
            ./docs/_static/export
            ./docs/_static/images
            ./docs/appendix/export
            ./julia-*/
            ~/.julia/
            ~/.sympy-cache*/
      - name: Install Julia
        run: |
          version=$(sed -n '3p' julia/Manifest.toml)
          version=${version:17:-1}
          major_version=${version:0:-2}
          filename=julia-${version}-linux-x86_64.tar.gz
          if [ ! -d julia-${version} ]; then
            wget -q https://julialang-s3.julialang.org/bin/linux/x64/${major_version}/${filename}
            tar xzf ${filename}
          fi
          sudo ln -s $(pwd)/julia-${version}/bin/julia /usr/local/bin/julia
          julia --version
          julia --project=./julia -e 'import Pkg; Pkg.instantiate()'
      - run: tox -e pdfnb
      - run: tox -e docnb
        env:
          EXECUTE_PLUTO: "YES"
      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: html
          path: |
            docs/_build/html
            docs/_build/latex

  gh-pages:
    name: Upload to GitHub Pages
    needs: documentation
    if: >
      github.repository == 'ComPWA/polarimetry' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - name: Remove all existing files
        run: find . ! -regex '^./.git\(/.*\)?' -delete | true
      - uses: actions/download-artifact@v3
        with:
          name: html
          path: .
      - name: Commit to gh-pages orphan branch
        run: |
          git checkout --orphan gh-pages
          git add -A
          git config --global user.name "GitHub"
          git config --global user.email "noreply@github.com"
          git status -s
          git commit -m "Upload documentation build files"
      - name: Force-push changes
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}
          git push origin gh-pages --force
