name: Style checks
env:
  PYTHON_VERSION: "3.8"

on:
  push:
    branches:
      - main
      - epic/*
      - "[0-9]+.[0-9]+.x"
  pull_request:
    branches:
      - main
      - epic/*
      - "[0-9]+.[0-9]+.x"
  workflow_dispatch:

jobs:
  pre-commit:
    name: Run local pre-commit hooks
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{env.PYTHON_VERSION}}
      - uses: actions/cache@v3
        with:
          key: pip-sty-${{runner.os}}-py${{env.PYTHON_VERSION}}-${{ hashFiles('.constraints/py3.*.txt', '.pre-commit-config.yaml') }}
          path: |
            ~/.cache/pip/
            ~/.cache/pre-commit/
      - run: pip install -e .[sty] -c .constraints/py${PYTHON_VERSION}.txt
      - name: Run pre-commit hooks that don't work on pre-commit.ci
        run: |-
          pre-commit run pyright -a --color always
