name: Unit tests

on:
  push:
    branches:
      - main
      - epic/*
      - "[0-9]+.[0-9]+.x"
  pull_request:
    branches:
      - main
      - epic/*
      - "[0-9]+.[0-9]+.x"
  workflow_dispatch:

jobs:
  pytest:
    name: Run pytest
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/cache@v3
        with:
          key: pip-test-${{matrix.os}}-${{hashFiles(.constraints/py${{matrix.python-version}}.txt, setup.cfg)}}
          path: ~/.cache/pip/
      - run: pip install -e .[test] -c .constraints/py${{matrix.python-version}}.txt
      - name: Run unit tests and doctests with pytest
        run: pytest -n auto
