name: Update Docker images

on:
  push:
    branches:
      - docker-images
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_BASE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    name: Build Docker image
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        job-name:
          - documentation
          - fast-pdf
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_BASE_NAME }}-${{ matrix.job-name }}
          tags: |
            type=schedule
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=branch
            type=ref,event=pr
            type=edge,branch=main
            type=sha
      - uses: docker/build-push-action@v4
        with:
          context: .
          file: .github/workflows/docker/Dockerfile.${{ matrix.job-name }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
