name: Push to GitLab

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push main branch to GitLab
        run: |
          git remote add gitlab "https://oauth2:${token}@gitlab.cern.ch/polarimetry/Lc2pKpi.git"
          git push gitlab main
        env:
          token: ${{ secrets.GITLAB_TOKEN }}
