name: Requirements

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
      - epic/*
    paths:
      - .constraints/py3.*.txt
      - .pre-commit-config.yaml
      - pyproject.toml
  schedule:
    - cron: "0 3 7 */3 *"
  workflow_dispatch:

jobs:
  requirements:
    uses: ComPWA/actions/.github/workflows/requirements.yml@v1
    secrets:
      token: ${{ secrets.PAT }}
